name: Build and Test

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
  macos:
    name: macOS test build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Build & Test
      run: swift test --enable-code-coverage
    - name: Convert coverage report
      run: xcrun llvm-cov export -format="lcov" .build/debug/swift-nio-ipPackageTests.xctest/Contents/MacOS/swift-nio-ipPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
  linux:
    name: Linux ${{ matrix.linux }} test build
    container:
      image: swift:${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: [bionic, xenial, focal, amazonlinux2, centos8]
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      if: ${{ !(startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' )) }}
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - name: Install libsqlite3
      if: ${{ startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' ) }}
      run: yum update -y && yum install -y sqlite-devel
    - name: Check Swift version
      run: swift --version
    - name: Build & Test
      run: swift test --enable-test-discovery
